### ISSUE TITLE
Add flip cards for members

### ISSUE THREAD

**Issue by BALaka-18** [gmelodie/debugs-bunnies#3]
We could have a section in the website where we'll be having flip cards for all members of the Pod, including the Pod Leader.
1. The front part of the card will have the name of the member and maybe a picture/social media icons for LinkedIn, Twitter, GitHub etc.
2. Upon hovering over the cards, they'll flip to show a brief 1 line of personal introduction or a crazy fun fact about that member.

We can have other ways to show members too.

**Comment by gmelodie** [comment]
Maybe this plus make the card clickable or include a button for more information

**Comment by APiligrim** [comment]
Based on brainstorming session from 3 weeks ago: 
- Links to inspirations / references: https://codingcrows.vercel.app/ 
- network connecting people and the grid animated
- flips & maybe gives brief summary (bio) 
- takes you to a page thats all personal

**Comment by APiligrim** [comment]
Honey comb picture screen: https://codepen.io/gabrielajohnson/pen/EMVxEL 
**Cool Hover squares: https://codepen.io/arthurcamara1/pen/KaMBZg (voted)**

**Comment by m0mosenpai** [comment]
https://codepen.io/hexagoncircle/pen/XWbWKwL
https://codepen.io/creativeocean/pen/mdROBXx

**Comment by m0mosenpai** [comment]
https://codepen.io/dev_loop/pen/MWKbJmO
This is the best one!!!!!!!
